stages:
  feature:
    cmd: python src/stages/featurize.py
    deps: 
    - 'src/data/data_shelter.csv'
    - src/stages/featurize.py
    params:
    - feature.test_size
    outs:
    - 'src/data/splits/test.csv'
    - 'src/data/splits/train.csv'


  train:
    cmd: python src/stages/train.py
    deps:
    - src/stages/train.py
    - 'src/data/splits/train.csv'
    params:
    - train.random_seed
    - train.lr
    - train.max_depth
    - train.n_estimators
    outs:
    - src/model/train.pkl

  evaluate:
    cmd: python src/stages/evaluate.py
    deps:
    - src/stages/evaluate.py
    - 'src/data/splits/test.csv'
    - src/model/train.pkl
    params:
    - test.random_seed 
    # outs:
    # - src/evaluation_artefacts/test.json
    metrics:
    - src/evaluation_artefacts/test.json:
       cache: false
