base:
  n_neighbors: 3
  random_seed: 42

data_load:
  dataset_csv: 'src/data/data_shelter.csv'

data_split:
  test_size: 0.2
feature:
  dataset_csv: 'src/data/data_shelter.csv'
  test_size: 0.2

train:
  # training parameters, hyperparameters
  dataset_csv : 'src/data/splits/train.csv'
  max_depth: 2
  random_seed: 42
  lr: 1
  n_estimators: 150

test: 
  dataset_csv: 'src/data/splits/test.csv'
  model: 'src/model/train.pkl'
  random_seed: 42


reports:
  # where we saving metrics, images